class RMQ_CONFIG():
    """RabbitMQ configuration"""
    RMQ_SERVER_IP = "localhost" #Andreas home:  10.0.0.228, Andreas drobotti: 192.168.0.165
    RMQ_SERVER_PORT = 5672
    MONITOR_EXCHANGE = "MONITOR_EXCHANGE"
    DT_EXCHANGE = "DT_EXCHANGE"
    DT_QUEUE_CONTROLLER = "DT_QUEUE_CONTROLLER"
    DT_QUEUE_MONITOR = "DT_QUEUE_MONITOR"
    CONTROLLER_EXCHANGE = "CONTROLLER_EXCHANGE"
    CONTROLLER_QUEUE = "CONTROLLER_QUEUE"
    FANOUT = "fanout"
    DIRECT = "direct"
    